### ISSUE TITLE
为什么是东雪莲

### ISSUE THREAD

**Issue by breadxiexie** [Selen-Suyue/AgentCrossTalk#1]
不是永雏塔菲我不看😡

**Comment by Selen-Suyue** [comment]
我们也尝试过嘉然Diana以及海子姐，最后选用星瞳和冬雪莲是因为这两款inference的速度相对较快（我们猜测是模型参数量导致的推理速度不同）。个人认为taffy的语音比较模糊并且有点抽象，不过你可以根据readme中提供的link定制你自己喜欢的模型。
